version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline
    ports: 
      - "8082:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
      - "$PWD/centos7/script.sh:/tmp/script1.sh"
    networks: 
      - net
  db_host:
    container_name: mysql
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=changeme"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
  Web:
    container_name: web
    image: ansible_web
    build:
      context: jenkins-data/web
    ports:
      - "80:80"
    networks:
      - net 
  git:
    container_name: git-server
    image: 'gitlab/gitlab-ee:latest'
    hostname: 'gitlab.local'
    ports:
      - '8084:80'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - net
networks:
  net:
